"""Add missing indexes to foreign keys

Revision ID: fca3ca35f96b
Revises: 
Create Date: 2026-07-07 11:11:22.982348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fca3ca35f96b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Safely drop legacy tables/indexes if they exist
    op.execute("DROP INDEX IF EXISTS ix_confidence_history_decision_case_id")
    op.execute("DROP TABLE IF EXISTS confidence_history CASCADE")
    op.execute("DROP INDEX IF EXISTS ix_approval_history_decision_case_id")
    op.execute("DROP TABLE IF EXISTS approval_history CASCADE")
    op.execute("DROP INDEX IF EXISTS ix_conflict_history_decision_case_id")
    op.execute("DROP TABLE IF EXISTS conflict_history CASCADE")

    # Safely create indexes
    op.execute("CREATE INDEX IF NOT EXISTS ix_ai_responses_decision_case_id ON ai_responses (decision_case_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_approval_requests_approved_by ON approval_requests (approved_by)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_approval_requests_decision_case_id ON approval_requests (decision_case_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_approval_requests_rejected_by ON approval_requests (rejected_by)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_approval_requests_requested_by ON approval_requests (requested_by)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_audit_logs_decision_case_id ON audit_logs (decision_case_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_audit_logs_user_id ON audit_logs (user_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_confidence_scores_ai_response_id ON confidence_scores (ai_response_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_conflict_logs_decision_case_id ON conflict_logs (decision_case_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_decision_cases_machine_id ON decision_cases (machine_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_decision_cases_user_id ON decision_cases (user_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_document_chunks_document_id ON document_chunks (document_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_documents_uploaded_by ON documents (uploaded_by)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_engineer_insights_engineer_id ON engineer_insights (engineer_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_engineer_insights_machine_id ON engineer_insights (machine_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_generated_reports_decision_case_id ON generated_reports (decision_case_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_generated_reports_generated_by ON generated_reports (generated_by)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_incidents_machine_id ON incidents (machine_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_inspection_reports_inspector_id ON inspection_reports (inspector_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_inspection_reports_machine_id ON inspection_reports (machine_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_maintenance_records_machine_id ON maintenance_records (machine_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_maintenance_records_technician_id ON maintenance_records (technician_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_notifications_user_id ON notifications (user_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_reasoning_memory_decision_case_id ON reasoning_memory (decision_case_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_sops_document_id ON sops (document_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_sops_machine_id ON sops (machine_id)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sops_machine_id'), table_name='sops')
    op.drop_index(op.f('ix_sops_document_id'), table_name='sops')
    op.drop_index(op.f('ix_reasoning_memory_decision_case_id'), table_name='reasoning_memory')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_maintenance_records_technician_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_machine_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_inspection_reports_machine_id'), table_name='inspection_reports')
    op.drop_index(op.f('ix_inspection_reports_inspector_id'), table_name='inspection_reports')
    op.drop_index(op.f('ix_incidents_machine_id'), table_name='incidents')
    op.drop_index(op.f('ix_generated_reports_generated_by'), table_name='generated_reports')
    op.drop_index(op.f('ix_generated_reports_decision_case_id'), table_name='generated_reports')
    op.drop_index(op.f('ix_engineer_insights_machine_id'), table_name='engineer_insights')
    op.drop_index(op.f('ix_engineer_insights_engineer_id'), table_name='engineer_insights')
    op.drop_index(op.f('ix_documents_uploaded_by'), table_name='documents')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_decision_cases_user_id'), table_name='decision_cases')
    op.drop_index(op.f('ix_decision_cases_machine_id'), table_name='decision_cases')
    op.drop_index(op.f('ix_conflict_logs_decision_case_id'), table_name='conflict_logs')
    op.drop_index(op.f('ix_confidence_scores_ai_response_id'), table_name='confidence_scores')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_decision_case_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_approval_requests_requested_by'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_rejected_by'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_decision_case_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_approved_by'), table_name='approval_requests')
    op.drop_index(op.f('ix_ai_responses_decision_case_id'), table_name='ai_responses')
    op.create_table('conflict_history',
    sa.Column('decision_case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('has_conflicts', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('overall_severity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('conflicts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('resolved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('resolved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('conflict_history_pkey'))
    )
    op.create_index(op.f('ix_conflict_history_decision_case_id'), 'conflict_history', ['decision_case_id'], unique=False)
    op.create_table('approval_history',
    sa.Column('decision_case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reviewer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('decision', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('previous_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('new_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('approval_history_pkey'))
    )
    op.create_index(op.f('ix_approval_history_decision_case_id'), 'approval_history', ['decision_case_id'], unique=False)
    op.create_table('confidence_history',
    sa.Column('decision_case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('component_scores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('confidence_history_pkey'))
    )
    op.create_index(op.f('ix_confidence_history_decision_case_id'), 'confidence_history', ['decision_case_id'], unique=False)
    # ### end Alembic commands ###
