"""
INDUS AI — Reasoning Memory API

POST /api/reasoning/store    — Create a reasoning record from a resolved Decision Case.
GET  /api/reasoning/similar  — Find similar previously-solved cases (Case-Based Reasoning).
"""

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.database import get_db
from app.core.security import get_current_user
from app.models.users import User
from app.reasoning_engine.reasoning_models import (
    ReasoningStoreRequest,
    ReasoningStoreResponse,
    SimilarCasesResponse,
)
from app.reasoning_engine.reasoning_service import ReasoningService

router = APIRouter()


@router.post("/store", response_model=ReasoningStoreResponse)
async def store_reasoning(
    payload: ReasoningStoreRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Create a reasoning record from a resolved Decision Case.

    Extracts and stores: problem, evidence, documents used, recommendation,
    outcome, and reusable lesson. If no lesson is provided, one is
    auto-generated by the Reasoning Analyzer.

    An audit log entry is created for every submission.
    """
    try:
        response = await ReasoningService.store_reasoning(db, current_user, payload)
        return response
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


@router.get("/similar", response_model=SimilarCasesResponse)
async def find_similar_cases(
    q: str = Query(..., min_length=1, description="Problem description to find similar cases for"),
    limit: int = Query(5, ge=1, le=20, description="Max number of similar cases to return"),
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Find similar previously-solved Decision Cases using Case-Based Reasoning.

    Searches across problem summaries, recommendations, and lessons learned.
    Results are ranked by similarity score, confidence, and recency.
    """
    return await ReasoningService.get_similar_cases(db, q, limit)
